# Modulüberblick

```{r include=TRUE}
library(yaml)
library(tidyverse)
```


```{r echo = FALSE}
source("https://raw.githubusercontent.com/sebastiansauer/Lehre/main/R-Code/render-course-sections.R")
```




## Modulzeitplan



```{r render-outline-course-small-table, results = "asis", echo = FALSE, message = FALSE}

course_dates_file <- here::here("course-dates.yaml")
content_file <- here::here("_modul-ueberblick.yaml")
link_stump <- "https://sebastiansauer.github.io/datascience1/"

stopifnot(file.exists(course_dates_file))
stopifnot(file.exists(content_file))

#debug(render_course_outline)
# render_course_outline(course_dates_file, content_file, small_table = TRUE, header_level = 3)


master_table <- build_master_course_table(course_dates_file, 
                                          content_file,
                                          link_type = 3,
                                          link_stump = link_stump)
master_table_short <- 
  master_table %>% 
  select(1,2,6, Titel_Link) 

knitr::kable(master_table_short)
```


## Beschreibung der Themen


```{r render-outline-course, results = "asis", echo = FALSE, message = FALSE}

course_dates_file <- here::here("course-dates.yaml")
content_file <- here::here("_modul-ueberblick.yaml")

stopifnot(file.exists(course_dates_file))
stopifnot(file.exists(content_file))

descriptors <- c(
 # "Titel", 
  "Lernziele", 
  "Literatur",
  "Vorbereitung", 
  "Aufgaben", 
  "Vertiefung", 
  "Hinweise"
  )

#debug(render_course_outline)
render_course_outline(course_dates_file, content_file, 
                      small_table = FALSE, 
                      descriptors = descriptors,
                      header_level = 3)
```

