
# Der rote Faden


## Lernsteuerung

### Überblick

Mittlerweile haben wir einiges zum Thema Data Science bzw. maschinelles Lernen behandelt (und sie hoffentlich viel gelernt).

Da ist es an der Zeit, einen Schritt zurück zu treten,
um sich einen Überblick über den gegangenen Weg zu verschaffen,
den berühmten "roten Faden" zu sehen, den zurückgelegten Weg nachzuzeichnen 
in den groben Linien, um einen (klareren) Überblick über das Terrain zu bekommen.

In diesem Kapitel werden wir verschiedene "Aussichtspfade" suchen, um im Bild zu bleiben,
die uns einen Überblick über das Gelände versprechen.

###  Lernziele
- Sie erarbeiten sich einen Überblick über den bisher gelernten Stoff bzw. verfeinern Ihren bestehenden Überblick


### Literatur
 - Rhys im Überblick








## Aussichtspunkt 1: Blick vom hohen Berg


Und so zeigt sich ein "Flussbild"^[Wem das Bild zu klein gezeichnet ist, der nehme entweder eine Lupe oder öffne das Bild per Rechtsklick in einem neuen Tab.] (@fig-fluss).



```{mermaid}
%%| label: fig-fluss
%%| fig-cap: Ein Flussbild des maschinellen Lernens

flowchart LR
  Vv[Vorverarbeitung] --> W[Workflow]
  MF[Modellformel] --> W[Workflow]
  Mo[Modell] --> W[Workflow]
  Al[Algorithmus] --> Mo
  Im[Implementierung] --> Mo
  Mod[Modus] --> Mo
  St[z.B. Standardisierung] --> Vv
  FW[z.B. Fehlende Werte] --> Vv
  W -- für jeden Workflow --> Tuning
  subgraph Tuning
subgraph Resampling
  subgraph Fitten
  end
end
  end
  Tuning --> bM[bester Modellkandidat]
  bM --> FT[Fitten auf ganz Train-Sample]
  FT --> PT[Predict auf Test-Sample]
  PT -->  MG[Modellgüte]
  MG --> num[numerisch]
  MG --> klas[klassifikatorisch]

```








Der Reiseführer erzählt uns zu diesem Bild folgende Geschichte:


{{< video https://www.youtube.com/embed/PO-UrF5hGtY >}}


<!-- <iframe width="560" height="315" src="https://www.youtube.com/embed/PO-UrF5hGtY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> -->

[Video-Geschichte](https://youtu.be/PO-UrF5hGtY)

## Aussichtspunkt 2: Blick in den Hof der Handwerker

Wenn man auf einem hohen Berg gestanden ist, hat man zwar einen guten Überblick über das Land bekommen,
aber das konkrete Tun bleibt auf solchen Höhen verborgen.

Möchte man wissen, wie das geschäftige Leben abläuft, muss man also den tätigen Menschen über die Schulter schauen.
Werfen wir also einen Blick in den "Hof der Handwerker",
wo grundlegende Werkstücke gefertigt werden,
und wir jeden Handgriff aus der Nähe mitverfolgen können.



### Ein maximale einfaches Werkstück mit Tidymodels

Weniger blumig ausgedrückt: Schauen wir uns ein maximal einfaches Beispiel an,
wie man mit Tidymodels Vorhersagen tätigt.
Genauer gesagt bearbeiten wir [einen sehr einfachen Ansatz](https://www.kaggle.com/code/ssauer/simple-linear-model-tidymodels) für einen Kaggle-Prognosewettbewerb.



<iframe width="560" height="315" src="https://www.youtube.com/embed/QHbIONGgMrA" frameborder="0" allowfullscreen></iframe>



### Ein immer noch recht einfaches Werkstück mit Tidymodels

Dieses Beispiel ist nur wenig aufwändiger als das vorherige.


<iframe width="560" height="315" src="https://www.youtube.com/embed/QS94JTMpnHc" frameborder="0" allowfullscreen></iframe>




## Aussichtspunkt 3: Der Nebelberg (Quiz)

Da der "Nebelberg" zumeist in Wolken verhüllt ist, muss man, wenn man ihn ersteigt und ins Land hinunterschaut,
erraten, welche Teile zu sehen sind. Sozusagen eine Art Landschafts-Quiz.

Voilà, hier ist es, das *Quiz* zum maschinellen Lernen:

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdw9ngLAcs7VMaF5P-nRSS8zCBjLdJyPYXsGTzy1ERmD6oPcQ/viewform?embedded=true" width="640" height="930" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>





## Aussichtspunkt 4: Der Exerzitien-Park

Wir stehen vor dem Eingang zu einem Park,
in dem sich viele Menschen an merkwürdigen Übungen, Exerzitien, befleißigen.
Vielleicht wollen Sie sich auch an einigen Übungen abhärten? Bitte schön,
lassen Sie sich nicht von mir aufhalten.


```{r yacsdas, results='asis', echo = FALSE}
url <- "https://raw.githubusercontent.com/sebastiansauer/Lehre/main/Material/yacsdas.md"
childtext <- readLines(url)
cat(childtext, sep="\n")
```



## Aussichtspunkt 5: In der Bibliothek


Einen Überblick über eine Landschaft gewinnt man nicht nur von ausgesetzten Wegpunkten aus,
sondern auch, manchmal, aus Schriftstücken.
Hier ist eine Auswahl an Literatur,
die Grundlagen zu unserem Landstrich erläutert.


- @rhys
- @silge_tidy_2022


Etwas weiter leiten uns diese Erzähler:

- @islr
- @kuhn



## Krafttraining

Um die Aussicht genießen zu können, muss man manchmal ausgesetzte Plätze 
in ~~schwindelerregenden~~ ~~einigermaßen steilen~~ als Hügel erkennbaren Höhen erreichen...

Sportliche Leistungen erreicht nur, wer trainiert ist.
Das ist im Land des Data Science nicht anders.

Hier ist eine Liste von Übungen, die Ihre Datenkraft stählen soll:

1. *Lerngruppe*: Den Wert einer Lerngruppe kann man kaum unterschätzen. Die Motivation, der Austausch, der Zwang seine Gedanken geordnet darzustellen, das wechselseitige Abfragen - diese Dinge machen eine Lerngruppe zu einem der wichtigsten Erfolgsgarant in Ihren Lernbemühungen.
2. *Exzerpte*: Exzerpte, Zusammenfassungen also, sind nötig, um von einer vermeintlichen "Jaja, easy, versthe ich alles" Oberflächen-Verarbeitung zu einem (ausgeprägterem) Tiefenverständnis vorzudringen.
3. *Aufgaben*: Manchmal stellt ein Dozent Aufgaben ein. Die Chance sollte man nutzen, denn zwar ist vieles in der Didaktikforschung noch unsicher, aber dass Aufgaben lösen beim Lernen hilft, und zwar viel, ist eines der wenigen unstrittigen Erkenntnisse.
4. *Fallstudien*: Ähnliches wie Aufgaben, die oft kleinteilig-akademisch angelegt sind, hilft die große Schwester der schnöden Aufgabe, die Fallstudie, beim Vordringen in Verständnistiefen.
5. *Lesen*: Ja, Lesen ist voll Old School. Aber so was Ähnliches wie Updaten der Brain-Software. Nützlich, weil die alte Software irgendwann nicht mehr supported wird.
6. *Forum*: Sie haben eine Frage, aber Sie können unmöglich ein paar Tage warten, bis Sie den Dozenten im Unterricht sprechen? Posten Sie die Frage in einem Forum! Vielleicht im Forum des Moduls oder aber in einem geeigneten Forum im Internet.
7. *Youtube*: Zwar wettern Dozentis gerne über die mangelnde Verarbeitungstiefe beim Fern schauen. Außerdem sind Lehrvideos didaktisch echt asbachuralt. Aber okay, manchmal und in überschaubarer Dosis ist ein Lehrvideo eine nützliche Ergänzung zu den übrigen Maßnahmen.





<!-- ## Aufgaben und Vertiefung -->


## Aufgaben


 
- [Einfache Random-Forest-Modellierung bei Kaggle (TMDB)](https://www.kaggle.com/code/ssauer/simple-rf-tuned)
- [Einfache Workflow-Set-Modellierung bei Kaggle (TMDB)](https://www.kaggle.com/code/ssauer/tmdb-xgboost-tidymodels)
- Bearbeiten Sie so viele Fallstudien der Fallstudiensammlung wie nötig, um den Stoff flüssig zu beherrschen

##  Vertiefung
- [Mathematische Grundlagen können Sie z.B. hier vertiefen](https://deisenroth.cc/publication/deisenroth-2020/)
- [Gute Fallstudie bei Kaggle für Regressionsprobleme: House Prices](https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques)
- [Sie möchten schnell ein Code-Schnipsel (öffentlich sichtbar) teilen? Probieren Sie Github Gists aus](https://gist.github.com/)









