bookdown::preview_chapter("020-Modulueberblick.Rmd")
bookdown::preview_chapter("040-Grundkonzepte.Rmd")
bookdown::preview_chapter("060-tidymodels1.Rmd")
bookdown::preview_chapter("070-knn.Rmd")
bookdown::preview_chapter("080-tidymodels2.Rmd")
bookdown::render_book("index.Rmd", output_format = "bookdown::bs4_book")
bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook")
bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book")
